### ISSUE TITLE
Config file where we define the mutual peers relations

### ISSUE THREAD

**Issue by jrmanes** [celestiaorg/devops#343]
Config file where we define the mutual peers relations, like: 
yaml file, 

```yaml
mutualPeers:
  - peers:
    - label: "app: bridge-1"
    - label: "app: full-1"
  - peers:
    - label: "app: bridge-2"
    - label: "app: full-2"
  - peers:
    - label: "app: bridge-2"
    - label: "app: full-3"
```

where we'll use labels for identifying the nodes, and their relations

**Comment by jrmanes** [comment]
the config file will look like:

```yaml
mutualPeers:
  - peers:
    - label: "app: bridge-1"
    - label: "app: full-1"
  - peers:
    - label: "app: bridge-2"
    - label: "app: full-2"
  - peers:
    - label: "app: bridge-2"
    - label: "app: full-3"
```
