### ISSUE TITLE
add field `trustedPeersPath` to config to allow users to specify the path to the file

### ISSUE THREAD

**Issue by jrmanes** [celestiaorg/devops#358]

**Comment by jrmanes** [comment]
done 👌 
the config now looks like:

```yaml
mutualPeers:
  - peers:
    - nodeName: "da-bridge-1-0"
      containerName: "da"
    - nodeName: "da-full-1-0"
      containerName: "da"
    trustedPeersPath: "/home/celestia/config"
```

the field `trustedPeersPath` is optional, if you leave it empty, the default path is `/tmp`
