### ISSUE TITLE
make setup of arabica aws as code

### ISSUE THREAD

**Issue by smuu** [celestiaorg/devops#510]
Manually steps done:

```
eksctl create cluster --region=eu-west-1 --name=arabica-aws --without-nodegroup  --version=1.27
eksctl create nodegroup --config-file=eks-cluster-node-group.yaml
eksctl create iamidentitymapping -f eks-cluster-node-group.yaml
```

```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
​
metadata:
  name: arabica-aws
  region: eu-west-1
​
managedNodeGroups:
  - name: ng-pool-infra-0
    labels: { role: workers, k8s.scaleway.com/pool-name: pool-infra-0 }
    instanceType: c5a.16xlarge
    desiredCapacity: 4
    volumeSize: 80
    privateNetworking: true
  - name: ng-pool-da-0
    labels: { role: workers, k8s.scaleway.com/pool-name: pool-infra-0 }
    instanceType: c5a.16xlarge
    desiredCapacity: 4
    volumeSize: 80
    privateNetworking: true
​
iamIdentityMappings:
  - arn: arn:aws:iam::506657148836:user/jose@celestia.org
    groups:
      - system:masters
    username: jose
  - arn: arn:aws:iam::506657148836:user/alexk@celestia.org
    groups:
      - system:masters
    username: alexk
  - arn: arn:aws:iam::506657148836:user/viet@celestia.org
    groups:
      - system:masters
    username: viet
  - arn: arn:aws:iam::506657148836:user/samuel@celestia.org
    groups:
      - system:masters
    username: samuel
```
