### ISSUE TITLE
Re-configure otel collector to push traces to jaeger for bootstrappers

### ISSUE THREAD

**Issue by derrandz** [celestiaorg/devops#89]
Example of otel-collector config that pushes to a jeager instance:
```
extensions:
  health_check:

receivers:
  otlp:
    protocols:
      grpc:
        # endpoint: "0.0.0.0:4317"
      http:
        # endpoint: "0.0.0.0:4318"

exporters:
  prometheus:
    endpoint: "otel-collector:8889"
    namespace: "testground"
    send_timestamps: true
    metric_expiration: 1800m 
  jaeger:
    endpoint: "jaeger:14250"
    tls:
      insecure: true

service:
  extensions: [health_check]
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [prometheus]
    traces:
      receivers: [otlp]
      processors: []
      exporters: [jaeger]
    
```

We can deploy a jaeger instance using the following docker image:
```
jaegertracing/all-in-one:latest
```

and expose the following ports:
```
- "16686:16686"
- "14268:14268"
- "14250:14250"
```
